# Generated by Django 6.1.1 on 2026-09-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_doctor_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='doctor',
        ),
    ]
