# Generated by Django 6.1.1 on 2026-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_rename_user_doctor_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='user',
        ),
    ]
