# Generated by Django 6.1.1 on 2026-09-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_user_patient_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
    ]
