# Generated by Django 6.1.1 on 2026-09-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_patient_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='patient',
        ),
    ]
