# Generated by Django 6.1.1 on 2026-09-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_user_patient_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
    ]
