# Generated by Django 6.1.1 on 2026-09-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
                ('department_description', models.TextField()),
            ],
        ),
    ]
