# Generated by Django 6.1.1 on 2026-09-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'permissions': [('complete_appointment', 'Can complete appointment')]},
        ),
    ]
