# Generated by Django 6.1.1 on 2026-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('C', 'Completed')], max_length=1),
        ),
    ]
